service: kibana-proxy
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
plugins:
functions:
  proxy:
    handler: handler.proxy
    events:
      - http:
          path: /
          method: any
    environment:
      URL: ${file(./config.yml):URL}
      AWS_SIGN_REQUESTS: ${file(./config.yml):AWS_SIGN_REQUESTS}
